version: '3.9'
services:
  backend:
    container_name: tacro-backend
    image: 'backend:latest'
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile

  postgres:
    image: postgres:14.10
    container_name: tacro-postgres
    restart: unless-stopped
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_URL}
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - ./../isup-postgres-data:/var/lib/postgresql/data

volumes:
  conf:
  vhost:
  html:
  cache:
    driver: local

networks:
  default:
    name: nginx-proxy
    external: true

